# .prettierrc or .prettierrc.yaml
trailingComma: 'es5'
tabWidth: 2
semi: true
singleQuote: true

overrides:
  - files: "manifest.json"
    options:
      tabWidth: 4

  - files: "settings.json"
    options:
      tabWidth: 4

  - files: "*.ts"
    options:
      tabWidth: 4
